### ISSUE TITLE
nettrine/orm + odm – konflikt v zavislostech

### ISSUE THREAD

**Issue by tomaskrejci79** [contributte/doctrine-odm#4]
Ahoj,

uspesne pouzivam nettrine/orm, ale pri pokusu o instalaci nettrine/odm to pise " nettrine/odm v0.1.0 requires nettrine/annotations ^0.6.0 → satisfiable by nettrine/annotations[v0.6.0, v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.".

nettrine/orm pouziva nettrine/annotations ^0.8.0. Poradite jak to vyresit?

Diky!

**Comment by solcik** [comment]
@tomaskrejci79 sorry for the delay.

Solved via https://github.com/nettrine/odm/pull/5 and released [v0.2.0](https://github.com/nettrine/odm/releases/tag/v0.2.0)
